import Head from 'next/head'
import Register from '../src/Components/Pages/Register'
import Header from '../src/Components/Pages/Header/Header'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Minutka</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>
      <Register/>
    </div>
  )
}
